### ISSUE TITLE
Bug: TypeError: e is undefined

### ISSUE THREAD

**Issue by rchincha** [project-zot/zui#385] opened 2023-09-13 16:06 UTC
**Describe the bug**

v2.0.0-rc6+
```
TypeError: e is undefined
    qx Home.jsx:140
[main.15ae206d.js:2:692701](https://aci-zot02.insieme.local/static/js/main.15ae206d.js)
    qx https://aci-zot02.insieme.local/static/js/main.15ae206d.js:2
```
**To Reproduce**

Go to home page and just open "inspect" on browser

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vrajashkr** [comment] 2024-03-16 11:43
I had a go at trying to reproduce this. I wasn't able to see any errors in the console when opening the Home page. Looks like the issue might have already been fixed.

Steps followed:
1. Download `zot-linux-amd64` from Github Releases for version 2.0.2.
2. Run zot with the config file: `examples/config-ui.json`.
3. Access: `http://localhost:8080/home`.
4. Observed no errors in the console.

Browser: Firefox 123.0.1 (64-bit)
OS: Ubuntu Linux 22.04 LTS

**Comment by andaaron** [comment] 2024-03-26 06:57
Let's close this. We can open a new one if we have more details.

**Closed by andaaron** 2024-03-26 06:57 UTC
